.TH lxqt-policykit-agent "1" "September 2012" "LxQt\-qt\ 0.5.0" "LxQt\-Qt\ Module"
.SH NAME
lxqt-policykit-agent \- Polkit agent for \fBLXDE-Qt\fR: the faster and lighter QT Desktop Environment
.SH SYNOPSIS
.B lxqt-policykit-agent
[\fICurrently No command line arguments\fR]
.br
.SH DESCRIPTION
This module handles policykit for \fBLXDE-Qt\fR. The polkit module, will perform 
security tast over scale action privilegies.
.P
The \fBLXDE-Qt modules\fR are desktop independent tools, 
and operate as daemons for the local user for desktop specific operations. 
.P
\fBLXDE-Qt\fR is an advanced, easy-to-use, and fast desktop environment based on Qt
technologies, ships several core desktop components, all of which are optional:
.P
 * Panel
 * Desktop
 * Application launcher
 * Settings center
 * Session handler
 * Polkit handler \fI(this)\fR
 * Display manager handler
.P
These components perform similar actions to those available in other desktop
environments, and their name is self-descriptive.  They are usually not launched
by hand but automatically, when choosing a LxQt\-Qt session in the Display
Manager.
.SH BEHAVIOR
The module detected on shares privilege escalation, and maintain a security dialog 
that ask for the user's key need for action.
.SH AUTOSTART
The module only are showed on \fBLXDE-Qt\fR desktop, but u can create an autostart action 
for u prefered desktop environment.
.SH "REPORTING BUGS"
Report bugs to https://github.com/LXDE-Qt/LXDE-Qt/issues
.SH "SEE ALSO"
\fBLXDE-Qt\fR it has been tailored for users who value simplicity, speed, and
an intuitive interface, also intended for less powerful machines. See:

.\" any module must refers to session app, for more info on start it
.P
\fBlxqt-session.1\fR  LXDE-Qt for manage LXDE-Qt complete environment
.P
\fBstart-lxqt.1\fR  LXDE-Qt display management independient starup.
.P
\fBlxqt-config-session.1\fR  LXDE-Qt application for performing session autostart applications
.P
.SH AUTHOR
This manual page was created by \fBPICCORO Lenz McKAY\fR \fI<mckaygerhard@gmail.com>\fR
for \fBLXDE-Qt\fR project and VENENUX GNU/Linux but can be used by others.
