.TH lxqt-policykit-agent "1" "January 2025" "LXQt 2.1.0" "LXQt Module"
.SH NAME
lxqt-policykit-agent \- Polkit agent for the \fBLXQt\fR desktop environment
.SH SYNOPSIS
.B lxqt-policykit-agent
.br
.SH DESCRIPTION
This module manages PolicyKit for \fBLXQt\fR. The authentication agent ensures that the
session user verifies their identity by authenticating either as themselves or as an
administrator.
.P
The \fBLXQt modules\fR are desktop independent tools and operate as daemons
for the local user for desktop specific operations.
.SH BEHAVIOR
The module detects privilege escalation on shared resources and presents a security dialog
requesting the user's password to proceed with the action.
.SH AUTOSTART
The module is only shown in \fBLXQt\fR desktop, but  it's possible to create an autostart
action in other desktop environments.
.SH "REPORTING BUGS"
Report bugs to https://github.com/lxqt/lxqt-pòlicykit/issues
.SH "SEE ALSO"
.\" any module must refers to session app, for more info on start it
.P
\fBlxqt-session.1\fR
.P
\fBlxqt-config-session.1\fR
.P
\fBlxqt-sudo\fR
